vim.api.nvim_set_hl(0, "SnacksIndent1", { fg = "#222222" })
vim.api.nvim_set_hl(0, "SnacksIndent2", { fg = "#333333" })
vim.api.nvim_set_hl(0, "SnacksIndent3", { fg = "#555555" })
vim.api.nvim_set_hl(0, "SnacksIndent4", { fg = "#777777" })
vim.api.nvim_set_hl(0, "SnacksIndent5", { fg = "#aaaaaa" })
vim.api.nvim_set_hl(0, "SnacksIndent6", { fg = "#dddddd" })
vim.api.nvim_set_hl(0, "SnacksIndent7", { fg = "#ffffff" })
